Fix prolog/*.pl lacking module header, otherwise SWI-Prolog complains
ERROR:    Domain error: `module_header' expected, found `:-use_module(library(plGL_defs))'

P.S This patch just merge plOpenGL-0.6.2.zip from http://www.sebity.com/plopengl/downloads.php (The source code in GitHub seems out of sync with the website. Both are called 0.6.2, but website version seems newer).